default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: app_user
  password: app_pass
  host: db

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
  username: app_user
  password: app_pass
  host: db

production:
  <<: *default
  database: app_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
